version: '3.7'
services:
  app:
    build:
     dockerfile: Dockerfile
     context: ./
    command: bin/dev
    entrypoint: /app/entrypoints/app-entrypoint.sh
    tty: true
    working_dir: /app
    volumes:
    - ./:/app
    ports:
    - 3000:3000
    restart: always
    depends_on:
    - db
    - redis

  redis:
   image: redis

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      
    volumes:
    - db_volume:/var/lib/mysql
    ports:
    - 3306:3306

volumes:
  db_volume: